-- 코드를 작성해주세요
SELECT C.ID, CASE WHEN D.RANK <= D.TOTAL*0.25 THEN 'CRITICAL' WHEN D.RANK <= D.TOTAL*0.5 THEN 'HIGH'
WHEN D.RANK <= D.TOTAL*0.75 THEN 'MEDIUM' ELSE 'LOW' END COLONY_NAME FROM ECOLI_DATA C JOIN (
SELECT A.*, @rank := @rank +1 AS `RANK`, @total AS `TOTAL` 
FROM (SELECT * FROM ECOLI_DATA ORDER BY SIZE_OF_COLONY DESC) A JOIN
(SELECT @rank := 0, @total :=(SELECT COUNT(*) FROM ECOLI_DATA)) B
    ) D ON C.ID=D.ID ORDER BY C.ID;